[package]
name = "fight-headless"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.11.1", features = ["dynamic_linking"] }
serde = "1.0.183"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
